site_name: DISCOtoolkit

nav:
  - Home: index.md
  - Tutorial:
    - Download Data: download_data.ipynb
    - Cell Type Annotation: CELLiD_celltype_annotation.ipynb
    - scEnrichment: scEnrichment.ipynb
    - Gene Search: Gene_search.ipynb
  - API: API.md

plugins:
  - search:
  - git-revision-date-localized:
      enable_creation_date: true
  - mkdocs-jupyter:
      include_source: true
      include_requirejs: true
      remove_tag_config:
        remove_input_tags:
          - hide_code

theme:
  name: material
  favicon: assets/images/Discologo_1.png
  logo: assets/images/LOGO_WITH_title.745f2743.svg  # Customize to our own logo
  features:
    - search.highlight
    - search.suggest
    - content.code.copy
    - content.code.annotate
    - navigation.indexes
    - navigation.top
    - navigation.footer
    - toc.integrate
    - header.autohide

  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: white # F7F9F3 change to this later
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode

    # Palette toggle for dark mode
    - scheme: slate
      primary: blue grey
      toggle:
        icon: material/weather-night
        name: Switch to light mode
  custom_dir: overrides

markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
        permalink: "&para;"
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets

extra:
  social:
    - icon: material/github
      link: 'https://github.com/JinmiaoChenLab/DISCOtoolkit_py'
      name: DISCOtoolkit on GitHub

  analytics:
    provider: google
    property: G-L6ST3F8LYM

repo_url: https://github.com/JinmiaoChenLab/DISCOtoolkit_py
repo_name: DISCOtoolkit

extra_css:
  - assets/stylesheets/custom-style.css

extra_javascript:
  - 'https://cdn.plot.ly/plotly-latest.min.js'